#! /bin/sh
PERL5LIB=./lib:/home/hirobanex/site_perl
export PERL5LIB

USER='hirobanex'
export USER

exec 2>&1
cd /home/hirobanex/project/Hirobanex
exec setuidgid hirobanex envuidgid hirobanex /home/hirobanex/perl5/perlbrew/perls/current/bin/start_server --port=127.0.0.1:5999 --interval=5 -- /home/hirobanex/perl5/perlbrew/perls/current/bin/plackup -E staging -s Starlet --max_workers=4 --max-reqs-per-child=50 --max-keepalive-reqs=1 ./assets/script/hirobanex.psgi
