#! /bin/sh
PERL5LIB=./lib:/home/hirobanex/site_perl
export PERL5LIB

USER='hirobanex'
export USER

exec 2>&1
cd /home/hirobanex/project/Hirobanex
exec setuidgid hirobanex envuidgid hirobanex /home/hirobanex/perl5/perlbrew/perls/current/bin/start_server --port=5000 --interval=5 -- /home/hirobanex/perl5/perlbrew/perls/current/bin/plackup -E staging -s Starlet -o 127.0.0.1 --workers=15 --preload-app --max-requests=1000 --disable-keepalive=1 ./assets/script/hirobanex.psgi
